### ISSUE TITLE
Unknown provider: hSweetAlertProvider <- hSweetAlert

### ISSUE THREAD

**Issue by greemwahr** [leftstick/angular-sweetalert#1]
I get unknown provider when I inject as dependency into my controller.

NB: My controller.js and app.js files are separate. Also I'm using with the ionic framework that uses angularJS 1.3

What could be the problem, thanks!

**Comment by leftstick** [comment]
Possible to provide code snippet? A plunker is good to help to locate where the issue is.

And BTW, the latest `angular-sweetalert` requires `0.4.2` of `sweetalert` since AMD and CMD support was added.

**Comment by greemwahr** [comment]
I can give you the snippets over here if that's okay, cause it will be hard
to recreate on plunker cause all my files are on local machine e.g ionic
and likewise.

**Comment by leftstick** [comment]
OK, code snippet is fine. Let's see how you import those dependencies, and how you used them?

**Comment by greemwahr** [comment]
Cool! First thing to note is that I’m using it in Ionic framework which comes bundled with angular 1.3.x or something like that.

In my app.js file I have this

app.js:

angular.module(‘myapp', ['ionic', 'ngCordova’])

.run(function($ionicPlatform, $cordovaToast) {
  $ionicPlatform.ready(function() {
    // Hide the accessory bar by default (remove this to show the accessory bar above the keyboard
    // for form inputs)
    if(window.cordova && window.cordova.plugins.Keyboard) {
      cordova.plugins.Keyboard.hideKeyboardAccessoryBar(true);
    }
    if(window.StatusBar) {
      // org.apache.cordova.statusbar required
      StatusBar.styleDefault();
    }
    if(window.Connection) {
        if(navigator.connection.type == Connection.NONE) {
            $cordovaToast.show('Can\'t connect to network. Please re-try', 'long', 'bottom').then(function(success) {
                console.log("The toast was shown");
            }, function(error) {
                console.log("The toast was not shown due to " + error);
            });
        }
    }
  });
})

then I have a controller
popUpCtrl.js:

angular.module(‘myapp').controller('popUpCtrl', ['$scope','hSweetAlert', popUpCtrl]);

function popUpCtrl($scope, sweet) {
    'use strict';

```
// A confirm dialog box to get the GPS location.
$scope.showConfirm = function() {
    sweet.show({
        title: ‘Hello',
        text: ‘Howdy there?',
        type: 'Warning',
        showCancelButton: true,
        confirmButtonColor: '#DD6B55',
        confirmButtonText: 'Yes',
        cancelButtonText: 'No',
        closeOnConfirm: false,
        closeOnCancel: false },

        function(isConfirm) {
            if(isConfirm) {
                sweet.show(‘Hello', ’SweetAlert is nice.', 'success');
            } else {
                sweet.show('Requirement!', ‘You should try using SweetAlertJS.', 'error');
            }
        });
    };
}
```

**Comment by leftstick** [comment]
You missed dependency of `angular-sweetalert`.

Something should be modified as following:

```
angular.module(‘myapp', ['ionic', 'ngCordova’])  =>   angular.module(‘myapp', ['ionic', 'ngCordova’, 'hSweetAlert'])




angular.module(‘myapp').controller('popUpCtrl', ['$scope','hSweetAlert', popUpCtrl]);  =>  angular.module(‘myapp').controller('popUpCtrl', ['$scope','sweet', popUpCtrl]);
```

**Comment by greemwahr** [comment]
Excellent!…… It works fine now, thanks a lot. Noobie mistake I made there with the controller bit. Thanks a lot again. One final thing, I can put an ngClick attribute in the Sweet-Alert.html file right? I need a function to be called when I press the OK button.

Cheers!

**Comment by leftstick** [comment]
You mean `sweetalert/lib/ Sweet-Alert.html`? This file is only used in development phase. You don't need it.

**Comment by greemwahr** [comment]
hmmmm! Okay, so how do I call a function when I click on the "Okay" or "Cancel" button?

**Comment by leftstick** [comment]
Check following code:

```
 sweet.show({
        title: 'Confirm',
        text: 'Delete this file?',
        type: 'warning',
        showCancelButton: true
    }, function(isOk) {
        if (isOk) {
            alert('OK is clicked');
        } else {
            alert('Cancel is clicked');
        }
    });
```

**Comment by greemwahr** [comment]
Thanks!
