### ISSUE TITLE
License

### ISSUE THREAD

**Issue by igorlino** [leftstick/angular-sweetalert#16]
Hi,

I just looked into the component, which seems quite nice. :)

The only thing that catch my eye was the license GPL3.

Would it make sense to better use the same license as the base library sweetalert2 ?  (MIT )
https://github.com/sweetalert2/sweetalert2/blob/master/LICENSE

Homogenous licenses makes it easier to adopt. MIT being the overwhelmed preferred choice for nearly all javascript libraries. 

Thanks

**Comment by leftstick** [comment]
agreed
