### ISSUE TITLE
Is it the same?

### ISSUE THREAD

**Issue by josemadev** [leftstick/angular-sweetalert#5]
https://github.com/tushariscoolster/ng-sweet-alert/graphs/contributors

**Comment by leftstick** [comment]
If you are asking if we all wrapper of [sweet-alert](https://github.com/t4t5/sweetalert), yes, we are.

But the two projects offer you different way to use sweetalert. 

Choose one you preferred.

**Comment by josemadev** [comment]
Thanks :dancer:
