### ISSUE TITLE
Problem with charset

### ISSUE THREAD

**Issue by GabrielSt** [leftstick/angular-sweetalert#6]
I can´t display characteres that have accent or something similar, did i miss something?

![Image error](http://i.imgur.com/Jm7fNx3.png)

**Comment by leftstick** [comment]
Can you provide a snippet?, i tried following words, and it worked:

![snip20151208_1](https://cloud.githubusercontent.com/assets/1059956/11646580/5647dc66-9d9a-11e5-8342-ca35dde1c501.png)

You need to make sure:

**Have you `javascript` file encoded as `utf-8`**, take [atom](https://atom.io/) for example:
![snip20151208_2](https://cloud.githubusercontent.com/assets/1059956/11646625/b8da63bc-9d9a-11e5-91f9-54ad0cbee48d.png)

**Have you browser encoded as `utf-8`**, take `chrome` for example:
![screen shot 2015-12-08 at 11 00 53 am](https://cloud.githubusercontent.com/assets/1059956/11646656/0b2760ac-9d9b-11e5-9c86-e3613d3ab44c.png)

And then, it should be fine

**Comment by GabrielSt** [comment]
I'm sorry about that.
It's just a visualstudio configuration for js files.

Thanks for the help.
