### ISSUE TITLE
Template option

### ISSUE THREAD

**Issue by antidote2** [leftstick/angular-sweetalert#7]
Hi I would like to use a template option.

Why this is important for my case: I'm using angular-translate. angular-translate directive does work, but the $translate service screws up when used with strategy sanitize. So all messages I display with sweet alert are escaped.

**Comment by leftstick** [comment]
Can you provide code snippet, or plunker would be better

**Comment by aeharding** [comment]
(IMHO)

I don't think sweet alert is what you want to use in this case; sweet alert is meant to be more simple.

For templates, I'd look at one of the various other angular modal options out there.

**Comment by antidote2** [comment]
They are not that sweet:) I found out that using html = true option
actually works. Also I think the styles should not be set on element
directly but via css class. Have problems styling the buttons. Don't want
to make my own build.

**Comment by leftstick** [comment]
@anatolibarski you don't have to make your own build, checkout [theme](https://github.com/t4t5/sweetalert#themes), provide your own theme css file will work

**Comment by antidote2** [comment]
I think providing a templateUrl Option (in case it's possible with sweetalert) would be a nice update, as I want to use it as a confirm,... dialog across the application. If sweetalert is not that flexible to allow this, you should probably close the issue. The theme behaviour is actually broken, but it is sweetalert's fault and another issue, so I will post it there. You can see it's broken in their own themes: they need to use !important to override background-color.

**Comment by antidote2** [comment]
already there: https://github.com/t4t5/sweetalert/issues/413

**Comment by leftstick** [comment]
For template issue, you can handle it by yourself, as following:

``` javascript
$http.get('template.html', {cache:$templateCache});
```
