### ISSUE TITLE
Is it possible to get a callback on closing an alert 'success' or 'error'?

### ISSUE THREAD

**Issue by pvlastaridis** [leftstick/angular-sweetalert#9]

**Comment by leftstick** [comment]
You mean like this: 

![screen shot 2016-06-12 at 12 27 19 pm](https://cloud.githubusercontent.com/assets/1059956/15988991/0fb22634-3099-11e6-9cbe-09d38eebd8cb.png)

Depends on the `ajax` response, you can do anything you like^^

**Comment by pvlastaridis** [comment]
I mean why can't you do this
sweet.show({'Thank you',   'Your form was submitted successfully',  'success',
               function() {window.location.assign('/app/index.html')});

so when the popup OK is pressed the you are redirected to home page.

However I found this is working

sweet.show({title: ''Thank you',   text: 'Your form was submitted successfully',   type: 'success'},
               function() {window.location.assign('/utp/index.html')});

Thanks for your immediate reply.
